# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 08:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zdm_api', '0002_package_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
