# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zdm_api', '0003_auto_20160910_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='zdm_api.Package'),
            preserve_default=False,
        ),
    ]
