# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zdm_api', '0003_auto_20160910_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='owner',
        ),
        migrations.AddField(
            model_name='dependency',
            name='name',
            field=models.CharField(default='1.0.0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependency',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='zdm_api.Version'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependency',
            name='version_constraint',
            field=models.CharField(default='=1.0.0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='name',
            field=models.CharField(default='1.0.0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='zdm_api.Package'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='dependency',
            unique_together=set([('name', 'parent')]),
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set([('name', 'parent')]),
        ),
    ]
