# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zdm_api', '0004_auto_20160912_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='readme',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='zip_file',
            field=models.FileField(default='', upload_to=b''),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dependency',
            unique_together=set([('parent', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set([('parent', 'name')]),
        ),
    ]
