# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zdm_api', '0005_auto_20160912_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='readme',
            field=models.TextField(blank=True),
        ),
    ]
