# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import zdm_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('zdm_api', '0006_auto_20160912_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='zip_file',
        ),
        migrations.AddField(
            model_name='version',
            name='archive',
            field=models.FileField(default='hgello', upload_to=zdm_api.models.archive_path),
            preserve_default=False,
        ),
    ]
