# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zdm_api', '0007_auto_20160912_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependency',
            old_name='version_constraint',
            new_name='constraint',
        ),
    ]
